Repository homeaway/datapull, pull requests merged in 2020-01, with the labels that each got.

#17 Initial Commit
  .gitignore
  api/pom.xml
  api/src/main/java/com/homeaway/datapullclient/config/DataPullClientConfig.java
  api/src/main/java/com/homeaway/datapullclient/config/DataPullProperties.java
  api/src/main/java/com/homeaway/datapullclient/config/EMRProperties.java
  api/src/main/java/com/homeaway/datapullclient/process/DataPullRequestProcessor.java
  api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
  api/src/main/java/com/homeaway/datapullclient/start/DatapullclientApplication.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-prod.yml
  api/src/main/resources/application-stage.yml
  api/src/main/resources/application-test.yml
  api/src/main/resources/application.yml
  api/src/main/resources/logback-spring.xml
  api/src/main/resources/overwrite_config.sc
  api/src/main/resources/read_application_config.sc
  api/src/main/resources/terraform/datapull_iam/create_user_and_roles.bat
  api/src/main/resources/terraform/datapull_iam/create_user_and_roles.sh
  api/src/main/resources/terraform/datapull_task/ecs_deploy.sh
  api/src/main/resources/terraform/datapull_task/variables.tf
  api/terraform/datapull_iam/create_user_and_roles.bat
  api/terraform/datapull_iam/create_user_and_roles.sh
  api/terraform/datapull_iam/datapull_user_and_roles.tf
  api/terraform/datapull_iam/variables.tf
  api/terraform/datapull_task/datapull_ecs.tf
  api/terraform/datapull_task/ecs_deploy.bat
  api/terraform/datapull_task/ecs_deploy.sh
  api/terraform/datapull_task/variables.tf
  core/pom.xml
  core/src/main/resources/application-dev.yml
  core/src/main/resources/application-prod.yml
  core/src/main/resources/application-stage.yml
  core/src/main/resources/application-test.yml
  core/src/main/resources/application.yml
  core/src/main/scala/config/AppConfig.scala
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/logging/DataPullLog.scala
  core/src/main/scala/security/Vault.scala
  docs/docs/aws_account_setup.md
  docs/docs/install_on_aws.md
  docs/docs/oracle_teradata_support.md
  docs/mkdocs.yml
  functional-test/.gitignore
  master_application_config-dev.yml
  master_application_config-prod.yml
  master_application_config-stage.yml
  master_application_config-test.yml
  master_application_config.yml
Labels: dependencies, documentation, enhancement

#23 Minor documentation and dependency fixes
  CHANGELOG.md
  README.md
  core/pom.xml
  docs/docs/index.md
  docs/docs/install_on_aws.md
  docs/docs/media/datapull_installation.png
  docs/docs/media/logo.png
  docs/docs/monitor_spark_ui.md
Labels: dependencies, documentation

#24 Documentation branch PR for https://github.com/homeaway/datapull/pull/23
  index.html
  install_on_aws/index.html
  media/datapull_installation.png
  media/logo.png
  monitor_spark_ui/index.html
  search/search_index.json
  sitemap.xml
  sitemap.xml.gz
Labels: documentation

#26 Support for Oracle and Teradata
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
Labels: enhancement

#27 Kafka related changes
  core/src/main/resources/Samples/Input_Json_Specification.json
  core/src/main/resources/Samples/Input_Sample_s3_to_kafka.json
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
Labels: documentation, enhancement

#29 Changes for coalesce
  core/src/main/resources/Samples/Input_Json_Specification.json
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
Labels: documentation, enhancement

#32 Coalesce bug fix
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
  core/src/main/scala/logging/DataPullLog.scala
Labels: bug
