Repository homeaway/datapull, pull requests merged in 2020-07, with the labels that each got.

#65 Fixes #64
  CHANGELOG.md
  README.md
  docs/docs/index.md
Labels: documentation

#69 fix #67 by removing redundant -x in install script
  CHANGELOG.md
  api/terraform/datapull_task/ecs_deploy.sh
Labels: bug

#71 Resolve Issue #70
  CHANGELOG.md
  README.md
  api/src/main/java/com/homeaway/datapullclient/config/EMRProperties.java
  api/terraform/datapull_iam/datapull_user_and_roles.tf
  api/terraform/datapull_task/datapull_ecs.tf
  core/pom.xml
  core/src/main/resources/Samples/Input_Sample_hive-to-filesystem.json
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
  core/src/main/scala/logging/DataPullLog.scala
  docs/docs/aws_account_setup.md
  docs/docs/custom_emr_ec2_role.md
  docs/docs/index.md
  docs/docs/install_on_aws.md
  docs/docs/media/logo.png
  docs/docs/media/logo_transparent.png
  docs/docs/resources/sample_custom_emr_ec2_role.tf
  docs/mkdocs.yml
Labels: documentation, enhancement

#75 Mssql windows authentication
  CHANGELOG.md
  core/pom.xml
  core/src/main/resources/Samples/Input_Json_Specification.json
  core/src/main/resources/Samples/Input_Sample_SQLServer_to_Cassandra_with_windows_authentication.json
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
Labels: documentation, enhancement
