Repository homeaway/datapull, pull requests merged in 2021-07, with the labels that each got.

#123 Markovarghese/0.1.40
  CHANGELOG.md
  core/docker_spark_server/Dockerfile
  core/src/main/resources/Samples/Input_Json_Specification.json
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
Labels: bug, documentation, enhancement

#124 Improve documentation
  README.md
  core/src/main/resources/Samples/Input_Json_Specification.json
  docs/docs/aws_account_setup.md
  docs/docs/oracle_teradata_support.md
  manual-tests/README.md
  manual-tests/mssql_dataset_to_mysql_to_mssql/README.md
Labels: documentation

#125 Bug fixes and enhancements for kafka, secret stores, etc
  CHANGELOG.md
  api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
  api/terraform/datapull_task/datapull_ecs.tf
  core/src/main/resources/Samples/Input_Json_Specification.json
  core/src/main/scala/core/Controller.scala
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/DataPull.scala
  core/src/main/scala/core/Migration.scala
  core/src/main/scala/helper/Helper.scala
  core/src/main/scala/logging/DataPullLog.scala
  core/src/main/scala/security/SecretService.scala
  core/src/main/scala/security/SecretStore.scala
  core/src/main/scala/security/SecretsManager.scala
  core/src/main/scala/security/Vault.scala
  docs/docs/access_secrets.md
  docs/mkdocs.yml
Labels: bug, deprecation, documentation, enhancement
