Repository homeaway/datapull, pull requests merged in 2021-03, with the labels that each got.

#97 Manual test to test MongoDB as destination
  CHANGELOG.md
  README.md
  core/docker_spark_server/Dockerfile
  core/pom.xml
  manual-tests/README.md
  manual-tests/filesystem_dataset_with_uuids_to_mongodb/README.md
  manual-tests/filesystem_dataset_with_uuids_to_mongodb/datapull_input.json
Labels: dependencies, documentation

#98 Manual test process, and fix issue related to using Kafka topic as destination
  CHANGELOG.md
  README.md
  core/pom.xml
  manual-tests/README.md
  manual-tests/filesystem_dataset_to_kafka/README.md
  manual-tests/filesystem_dataset_to_kafka/datapull_input.json
  manual-tests/filesystem_dataset_to_kafka/docker_kafka_server/Dockerfile-confluenthub
  manual-tests/filesystem_dataset_to_kafka/docker_kafka_server/docker-compose.yml
  manual-tests/filesystem_dataset_with_uuids_to_mongodb/README.md
Labels: bug, dependencies, documentation

#101 Update Migration.scala
  CHANGELOG.md
  core/src/main/scala/core/Migration.scala
Labels: bug

#100 Support for string event format for Kafka destinations
  .gitattributes
  CHANGELOG.md
  api/terraform/datapull_task/ecs_deploy.sh
  core/src/main/resources/Samples/Input_Json_Specification.json
  core/src/main/resources/Samples/Input_Sample_s3_to_kafka.json
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
  manual-tests/filesystem_dataset_to_kafka/README.md
  manual-tests/filesystem_dataset_to_kafka/datapull_input.json
Labels: bug, enhancement
