Repository homeaway/datapull, pull requests merged in 2021-06, with the labels that each got.

#119 0.1.37 Streaming enhancements
  CHANGELOG.md
  CONTRIBUTING.md
  api/README.md
  core/pom.xml
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/Migration.scala
  core/src/main/scala/helper/Helper.scala
Labels: enhancement

#121 add dependency
  CHANGELOG.md
  core/pom.xml
Labels: dependencies

#122 Streaming enhancements and bugfixes, inline expression support, sequencefile support
  CHANGELOG.md
  core/src/main/resources/Samples/Input_Json_Specification.json
  core/src/main/scala/core/DataFrameFromTo.scala
  core/src/main/scala/core/DataPull.scala
  core/src/main/scala/core/Migration.scala
  core/src/main/scala/helper/Helper.scala
  manual-tests/filesystem_dataset_to_elasticsearch_to_filesystem/README.md
  manual-tests/filesystem_dataset_to_elasticsearch_to_filesystem/datapull_input.json
Labels: bug, documentation, enhancement
