Repository homeaway/datapull, pull requests merged in 2022-06, with the labels that each got.

#154 Update log4j Versions
  CHANGELOG.md
  core/pom.xml
  functional-test/pom.xml
Labels: dependencies

#157 Fix "logging level"
  CHANGELOG.md
  core/src/main/scala/helper/Helper.scala
Labels: bug

#158 Adding functionality for sending additional arguments as part of the …
  CHANGELOG.md
  api/src/main/java/com/homeaway/datapullclient/input/ClusterProperties.java
  api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
  api/src/main/resources/overwrite_config.sc
  api/src/main/resources/read_application_config.sc
  core/src/main/resources/Samples/Input_Json_Specification.json
Labels: enhancement, documentation

#159 Bootstrapfile conf
  CHANGELOG.md
  api/src/main/java/com/homeaway/datapullclient/input/ClusterProperties.java
  api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
  api/src/main/resources/overwrite_config.sc
  api/src/main/resources/read_application_config.sc
  core/src/main/resources/Samples/Input_Json_Specification.json
Labels: enhancement, documentation
