Repository homeaway/datapull, pull requests merged in 2022-07, with the labels that each got.

#163 Log4j
  CHANGELOG.md
  api/src/main/java/com/homeaway/datapullclient/config/EMRProperties.java
Labels: bug

#164 Update documentation for SFTP
  CHANGELOG.md
  core/src/main/resources/Samples/Input_Sample_s3_SFTP.json
  docs/docs/sftp.md
Labels: documentation

#165 adding functionality for providing arguments for bootstrapaction file…
  CHANGELOG.md
  api/src/main/java/com/homeaway/datapullclient/input/ClusterProperties.java
  api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
  core/src/main/resources/Samples/Input_Json_Specification.json
Labels: enhancement
